PRAGMA foreign_keys;
PRAGMA foreign_keys=ON;
CREATE TABLE publisher(id INTEGER PRIMARY KEY,name TEXT NOT NULL,country TEXT NOT NULL);
CREATE TABLE books(id INTEGER PRIMARY KEY,title TEXT NOT NULL,publisher INTEGER NOT NULL,FOREIGN KEY(publisher) REFERENCES publisher(id));
CREATE TABLE subjects(id INTEGER PRIMARY KEY,name TEXT NOT NULL);
CREATE TABLE books_subjects(book INTEGER NOT NULL,FOREIGN KEY(book) REFERENCES books(id),subject INTEGER NOT NULL,FOREIGN KEY(subject) REFERENCES subjects(id));

